service: magento

package:
  individually: true
  exclude:
    - ./**

provider:
  name: openwhisk
  runtime: nodejs:10
  ignore_certs: true
  defaultService: magento
  service: ${opt:service, self:provider.defaultService}

custom:
  npm-version: ${file(package.json):name}@${file(package.json):version}
  ow-package: ${opt:ow-package, self:custom.npm-version}
  concurrency: 200

plugins:
  - serverless-openwhisk
  - serverless-webpack

resources:
  packages: ${file(../common/serverlessPackageConfig.js)}

functions:
  getCartService:
    name: ${self:custom.ow-package}/getCartService
    handler: getCart.main
    concurrency: ${self:custom.concurrency}

  postCartService:
    name: ${self:custom.ow-package}/postCartService
    handler: postCartEntry.main
    concurrency: ${self:custom.concurrency}

  postCartEntryService:
    name: ${self:custom.ow-package}/postCartEntryService
    handler: postCartEntry.main
    concurrency: ${self:custom.concurrency}

  putCartEntryService:
    name: ${self:custom.ow-package}/putCartEntryService
    handler: putCartEntry.main
    concurrency: ${self:custom.concurrency}

  deleteCartEntryService:
    name: ${self:custom.ow-package}/deleteCartEntryService
    handler: deleteCartEntry.main
    concurrency: ${self:custom.concurrency}

  postBillingAddressService:
    name: ${self:custom.ow-package}/postBillingAddressService
    handler: postBillingAddress.main
    concurrency: ${self:custom.concurrency}

  deleteBillingAddressService:
    name: ${self:custom.ow-package}/deleteBillingAddressService
    handler: deleteBillingAddress.main
    concurrency: ${self:custom.concurrency}

  postShippingAddressService:
    name: ${self:custom.ow-package}/postShippingAddressService
    handler: postShippingAddress.main
    concurrency: ${self:custom.concurrency}

  deleteShippingAddressService:
    name: ${self:custom.ow-package}/deleteShippingAddressService
    handler: deleteShippingAddress.main
    concurrency: ${self:custom.concurrency}

  postShippingMethodService:
    name: ${self:custom.ow-package}/postShippingMethodService
    handler: postShippingMethod.main
    concurrency: ${self:custom.concurrency}

  deleteShippingMethodService:
    name: ${self:custom.ow-package}/deleteShippingMethodService
    handler: deleteShippingMethod.main
    concurrency: ${self:custom.concurrency}

  getShippingMethodsService:
    name: ${self:custom.ow-package}/getShippingMethodsService
    handler: getShippingMethods.main
    concurrency: ${self:custom.concurrency}

  getPaymentMethodsService:
    name: ${self:custom.ow-package}/getPaymentMethodsService
    handler: getPaymentMethods.main
    concurrency: ${self:custom.concurrency}

  postPaymentService:
    name: ${self:custom.ow-package}/postPaymentService
    handler: postPayment.main
    concurrency: ${self:custom.concurrency}

  postCartPaymentService:
    name: ${self:custom.ow-package}/postCartPaymentService
    handler: postCartPayment.main
    concurrency: ${self:custom.concurrency}

  deletePaymentService:
    name: ${self:custom.ow-package}/deletePaymentService
    handler: deletePayment.main
    concurrency: ${self:custom.concurrency}

  deleteCartPaymentService:
    name: ${self:custom.ow-package}/deleteCartPaymentService
    handler: deleteCartPayment.main
    concurrency: ${self:custom.concurrency}

  postCouponService:
    name: ${self:custom.ow-package}/postCouponService
    handler: postCoupon.main
    concurrency: ${self:custom.concurrency}

  deleteCouponService:
    name: ${self:custom.ow-package}/deleteCouponService
    handler: deleteCoupon.main
    concurrency: ${self:custom.concurrency}