version: 2
jobs:
  build:
    docker:
      - image: adobe/commerce-cif-ci-env:v0.0.1
    steps:
      - checkout
      - run:
          name: Build
          command: node ci/build.js
      - store_test_results:
          path: test/results
      - store_artifacts:
          path: test/results
      - store_artifacts:
          path: audit.json
  release:
    docker:
      - image: adobe/commerce-cif-ci-env:v0.0.1
    steps:
      - checkout
      - run:
          name: Release
          command: node ci/release.js
  deploy:
    docker:
      - image: adobe/commerce-cif-ci-env:v0.0.1
    steps:
      - checkout
      - run:
          name: Deploy
          command: node ci/deploy.js

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^@(.+)@release-(major|minor|patch)$/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^@adobe\/(.*)-[\d]+.[\d]+.[\d]+$/