version: 2
jobs:
  build:
    docker:
      - image: adobe/commerce-cif-ci-env:v0.0.1
    steps:
      - checkout
      - run:
          name: Build
          command: node ci/build.js
      - store_test_results:
          path: test/results
      - store_artifacts:
          path: test/results
  release:
    docker:
      - image: adobe/commerce-cif-ci-env:v0.0.1
    steps:
      - checkout
      - run:
          name: Release
          command: node ci/release.js

workflows:
  version: 2
  build-and-release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^@(.+)@release-(major|minor|patch)$/ 