service: my-custom-service

package:
  individually: true
  exclude:
    - ./**

provider:
  name: openwhisk
  runtime: nodejs:10
  ignore_certs: true

custom:
  # Adobe I/O Runtime configuration. The variables can be overriden by command-line arguments.
  customer-namespace: ${opt:customer-namespace, file(environment.json):CUSTOMER_NAMESPACE}
  customer-package: ${opt:customer-package, file(environment.json):CUSTOMER_PACKAGE}
  bindings-namespace: ${opt:bindings-namespace, file(environment.json):BINDINGS_NAMESPACE}

  # These variables define the names of the package bindings that will be created in the customer namespace
  common-actions: /${self:custom.customer-namespace}/commerce-cif-magento-common@latest
  carts-actions: /${self:custom.customer-namespace}/commerce-cif-magento-cart@latest
  orders-actions: /${self:custom.customer-namespace}/commerce-cif-magento-order@latest
  categories-actions: /${self:custom.customer-namespace}/commerce-cif-magento-category@latest
  customers-actions: /${self:custom.customer-namespace}/commerce-cif-magento-customer@latest
  products-actions: /${self:custom.customer-namespace}/commerce-cif-magento-product@latest

plugins:
  - '@cruglobal/serverless-merge-config' # provides the $<<: operator
  - serverless-openwhisk

# This defines the packages that will be deployed in the customer namespace
# Note that we cannot reuse the names defined above because one cannot use variables in YAML keys
# Important: this example creates and binds to '@latest' packages. In a production project, one should
# bind to released versions because '@latest' may in the future include backwards incompatible changes.
# To bind to a particular version, just replace '@latest' with the desired version like e.g. '@1.0.0'
resources:
  packages:
    magento:
      parameters:
    commerce-cif-magento-cart@latest:
      binding: /${self:custom.bindings-namespace}/commerce-cif-magento-cart@latest
      parameters:
        default_method: flatrate
        default_carrier: flatrate
        $<<: ${file(environment.json)}
    commerce-cif-magento-order@latest:
      binding: /${self:custom.bindings-namespace}/commerce-cif-magento-order@latest
      parameters:
        ${file(environment.json)}
    commerce-cif-magento-category@latest:
      binding: /${self:custom.bindings-namespace}/commerce-cif-magento-category@latest
      parameters:
        cachetime: 300
        $<<:
          - ${file(environment.json)}
          - ${file(credentials.json)}
    commerce-cif-magento-customer@latest:
      binding: /${self:custom.bindings-namespace}/commerce-cif-magento-customer@latest
      parameters:
        ${file(environment.json)}
    commerce-cif-magento-product@latest:
      binding: /${self:custom.bindings-namespace}/commerce-cif-magento-product@latest
      parameters:
        cachetime: 300
        $<<:
          - ${file(environment.json)}
          - ${file(credentials.json)}
    commerce-cif-magento-common@latest:
      binding: /${self:custom.bindings-namespace}/commerce-cif-magento-common@latest

# To prevent that your actions are publicly available to anyone, you can add the
# 'require-whisk-auth: my-secret' annotation to all the actions below
# HTTP requests will then have to include the HTTP header 'X-Require-Whisk-Auth: my-secret'
functions:

  getCart:
    name: ${self:custom.customer-package}/getCart
    sequence:
      - ${self:custom.carts-actions}/getCartService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  postCart:
    name: ${self:custom.customer-package}/postCart
    sequence:
      - ${self:custom.carts-actions}/postCartService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  postCartEntry:
    name: ${self:custom.customer-package}/postCartEntry
    sequence:
      - ${self:custom.carts-actions}/postCartEntryService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  putCartEntry:
    name: ${self:custom.customer-package}/putCartEntry
    sequence:
      - ${self:custom.carts-actions}/putCartEntryService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  deleteCartEntry:
    name: ${self:custom.customer-package}/deleteCartEntry
    sequence:
      - ${self:custom.carts-actions}/deleteCartEntryService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  postBillingAddress:
    name: ${self:custom.customer-package}/postBillingAddress
    sequence:
      - ${self:custom.carts-actions}/postBillingAddressService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  deleteBillingAddress:
    name: ${self:custom.customer-package}/deleteBillingAddress
    sequence:
      - ${self:custom.carts-actions}/deleteBillingAddressService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  postShippingAddress:
    name: ${self:custom.customer-package}/postShippingAddress
    sequence:
      - ${self:custom.carts-actions}/postShippingAddressService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  deleteShippingAddress:
    name: ${self:custom.customer-package}/deleteShippingAddress
    sequence:
      - ${self:custom.carts-actions}/deleteShippingAddressService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  postShippingMethod:
    name: ${self:custom.customer-package}/postShippingMethod
    sequence:
      - ${self:custom.carts-actions}/postShippingMethodService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  deleteShippingMethod:
    name: ${self:custom.customer-package}/deleteShippingMethod
    sequence:
      - ${self:custom.carts-actions}/deleteShippingMethodService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  getShippingMethods:
    name: ${self:custom.customer-package}/getShippingMethods
    sequence:
      - ${self:custom.carts-actions}/getShippingMethodsService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  getPaymentMethods:
      name: ${self:custom.customer-package}/getPaymentMethods
      sequence:
        - ${self:custom.carts-actions}/getPaymentMethodsService
        - ${self:custom.common-actions}/webActionTransformer
      annotations:
        web-export: true

  postPayment:
    name: ${self:custom.customer-package}/postPayment
    sequence:
      - ${self:custom.carts-actions}/postPaymentService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  postCartPayment:
      name: ${self:custom.customer-package}/postCartPayment
      sequence:
        - ${self:custom.carts-actions}/postCartPaymentService
        - ${self:custom.common-actions}/webActionTransformer
      annotations:
        web-export: true

  deletePayment:
    name: ${self:custom.customer-package}/deletePayment
    sequence:
      - ${self:custom.carts-actions}/deletePaymentService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  deleteCartPayment:
      name: ${self:custom.customer-package}/deleteCartPayment
      sequence:
        - ${self:custom.carts-actions}/deleteCartPaymentService
        - ${self:custom.common-actions}/webActionTransformer
      annotations:
        web-export: true

  postCoupon:
    name: ${self:custom.customer-package}/postCoupon
    sequence:
      - ${self:custom.carts-actions}/postCouponService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  deleteCoupon:
    name: ${self:custom.customer-package}/deleteCoupon
    sequence:
      - ${self:custom.carts-actions}/deleteCouponService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  postOrder:
    name: ${self:custom.customer-package}/postOrder
    sequence:
      - ${self:custom.orders-actions}/postOrderService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  getCategories:
    name: ${self:custom.customer-package}/getCategories
    sequence:
      - ${self:custom.categories-actions}/getCategoriesService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  getCategoryById:
    name: ${self:custom.customer-package}/getCategoryById
    sequence:
      - ${self:custom.categories-actions}/getCategoriesService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  getCategoryBySlug:
    name: ${self:custom.customer-package}/getCategoryBySlug
    sequence:
      - ${self:custom.categories-actions}/getCategoriesService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  getCustomerById:
    name: ${self:custom.customer-package}/getCustomerById
    sequence:
      - ${self:custom.customers-actions}/getCustomerByIdService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  postCustomerLogin:
    name: ${self:custom.customer-package}/postCustomerLogin
    sequence:
      - ${self:custom.customers-actions}/postCustomerLoginService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  postCustomerAuth:
    name: ${self:custom.customer-package}/postCustomerAuth
    sequence:
      - ${self:custom.customers-actions}/postCustomerAuthService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  getCustomer:
    name: ${self:custom.customer-package}/getCustomer
    sequence:
      - ${self:custom.customers-actions}/getCustomerService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  getProductById:
    name: ${self:custom.customer-package}/getProductById
    sequence:
      - ${self:custom.products-actions}/getProductByIdService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  getProductBySlug:
    name: ${self:custom.customer-package}/getProductBySlug
    sequence:
      - ${self:custom.products-actions}/getProductBySlugService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true

  searchProducts:
    name: ${self:custom.customer-package}/searchProducts
    sequence:
      - ${self:custom.products-actions}/searchProductsService
      - ${self:custom.common-actions}/webActionTransformer
    annotations:
      web-export: true