service: magento

package:
  individually: true
  exclude:
    - ./**

provider:
  name: openwhisk
  runtime: nodejs:10
  ignore_certs: true
  defaultService: magento
  service: ${opt:service, self:provider.defaultService}

custom:
  npm-version: ${file(package.json):name}@${file(package.json):version}
  ow-package: ${opt:ow-package, self:custom.npm-version}
  concurrency: 200

plugins:
  - serverless-openwhisk
  - serverless-webpack

resources:
  packages: ${file(../common/serverlessPackageConfig.js)}

functions:
  getCustomerByIdService:
    name: ${self:custom.ow-package}/getCustomerByIdService
    handler: getCustomerById.main
    concurrency: ${self:custom.concurrency}

  postCustomerLoginService:
    name: ${self:custom.ow-package}/postCustomerLoginService
    handler: postCustomerLogin.main
    concurrency: ${self:custom.concurrency}

  postCustomerAuthService:
    name: ${self:custom.ow-package}/postCustomerAuthService
    handler: postCustomerAuth.main
    concurrency: ${self:custom.concurrency}

  getCustomerService:
    name: ${self:custom.ow-package}/getCustomerService
    handler: getCustomer.main
    concurrency: ${self:custom.concurrency}