service: magento

package:
  individually: true
  exclude:
    - ./**

provider:
  name: openwhisk
  runtime: nodejs:10
  ignore_certs: true
  defaultService: magento
  service: ${opt:service, self:provider.defaultService}

custom:
  npm-version: ${file(package.json):name}@${file(package.json):version}
  ow-package: ${opt:ow-package, self:custom.npm-version}
  concurrency: 200

plugins:
  - serverless-openwhisk
  - serverless-webpack

resources:
  packages: ${file(../common/serverlessPackageConfig.js)}

functions:
  getCategoriesService:
    name: ${self:custom.ow-package}/getCategoriesService
    handler: getCategories.main
    concurrency: ${self:custom.concurrency}